use text files for Probeset
genenetwork/genenetwork2 pull request #727
Opened 2022-08-30 22:45 UTC by Alexanderlacuna

GN1 uses text files for huge probeset dataset contains strain values.This is an implementation for gn2

2022-09-06 21:19 UTC, Alexanderlacuna commented
@zsloan  could you try this out and give feedback.
@fredmanglis   @BonfaceKilz  this is ready for review

2022-09-07 02:32 UTC, fredmanglis approved these changes
Looks good. LGTM

*nitpick*: Do 

```python
if results:
    ...
```
rather than
```python
if (results):
    ...
```
unless the conditional is particularly long and needs to be broken into multiple lines.

2022-09-07 02:33 UTC, fredmanglis approved these changes
commit 9ee7efd8b18d8caece9cf8d3cc1d58ecbcf209a6

LGTM

2022-09-07 02:34 UTC, fredmanglis approved these changes
commit d6c8505606b7b9fa1e41b3ee8bca303a0f8d6597

LGTM

2022-09-07 03:03 UTC, fredmanglis requested changes
commit 6652c3137ec477e02c8291ee6154f24cc3a4cef2

@Alexanderlacuna 

You could use Python's inbuilt [CSV module](https://docs.python.org/3.9/library/csv.html) to parse and dump csv files.

I notice that `parse_line_csv` <sup>1</sup> splits the line into separate values, only for you to [then rejoin them](https://github.com/genenetwork/genenetwork2/pull/727/commits/6652c3137ec477e02c8291ee6154f24cc3a4cef2#diff-47cc07d4d9855d77c1030d0849ba82b992017d7c6bdf14d04d824e121f53cb14R215-R216). What is the point of that? You are doing an operation only to undo it - this is a performance drag (probably not big, but still a performance drag).

The `parse_line_csv` <sup>1</sup> could probably be cleaned up to be clearer on what is happening. The code mutates the `return_list` in a way that is not immediately apparent. It seems to be processing a list of lists, yet parsing a CSV file line would mostly give you non-nested list.

I'm still confused about how this function works. Could you give an example.

I find it difficult to merge this without understanding it. Maybe add a test with a sample file to be read so as to verify it works as expected.

### Footnotes

1 [`parse_line_csv`](https://github.com/genenetwork/genenetwork2/pull/727/commits/6652c3137ec477e02c8291ee6154f24cc3a4cef2#diff-47cc07d4d9855d77c1030d0849ba82b992017d7c6bdf14d04d824e121f53cb14R191-R195)

2022-09-07 03:05 UTC, fredmanglis commented
@Alexanderlacuna Please see the review comments and make the appropriate changes and resubmit for review.

2022-09-07 07:42 UTC, BonfaceKilz requested changes

2022-09-07 07:42 UTC, BonfaceKilz commented on wqflask/wqflask/correlation/pre_computes.py
> +        cursor.execute(query)
**tip:** Notice you only use query once.  Thus just pass it directly to the execute method.

**issue:** Please use %s like so:
```suggestion
        cursor.execute("SELECT Id, FullName FROM ProbeSetFreeze WHERE Name = %s", (dataset_name,))
```

This sanitizes the string for you and prevents and sql injection from any malicious source.

2022-09-07 07:42 UTC, BonfaceKilz commented on wqflask/wqflask/correlation/pre_computes.py
> +                              for line in file_handler.readlines()])
**issue:** As @fredmanglis mentioned, use python's inbuilt csv module to parse csv files.

2022-09-07 15:46 UTC, Alexanderlacuna commented
> commit [6652c31](https://github.com/genenetwork/genenetwork2/commit/6652c3137ec477e02c8291ee6154f24cc3a4cef2)
> 
> @Alexanderlacuna
> 
> You could use Python's inbuilt [CSV module](https://docs.python.org/3.9/library/csv.html) to parse and dump csv files.
> 
> I notice that `parse_line_csv` 1 splits the line into separate values, only for you to [then rejoin them](https://github.com/genenetwork/genenetwork2/pull/727/commits/6652c3137ec477e02c8291ee6154f24cc3a4cef2#diff-47cc07d4d9855d77c1030d0849ba82b992017d7c6bdf14d04d824e121f53cb14R215-R216). What is the point of that? You are doing an operation only to undo it - this is a performance drag (probably not big, but still a performance drag).
> 
> The `parse_line_csv` 1 could probably be cleaned up to be clearer on what is happening. The code mutates the `return_list` in a way that is not immediately apparent. It seems to be processing a list of lists, yet parsing a CSV file line would mostly give you non-nested list.
> 
> I'm still confused about how this function works. Could you give an example.
> 
> I find it difficult to merge this without understanding it. Maybe add a test with a sample file to be read so as to verify it works as expected.
> 
> ### Footnotes
> 1 [`parse_line_csv`](https://github.com/genenetwork/genenetwork2/pull/727/commits/6652c3137ec477e02c8291ee6154f24cc3a4cef2#diff-47cc07d4d9855d77c1030d0849ba82b992017d7c6bdf14d04d824e121f53cb14R191-R195)

@fredmanglis  This has to do with the bad formatting  of the current text files being used and makes it impossible to parse with as csv for example
the values for each are quoted as shown below
'"1415918_a_at","13.948","14.247","13.965","14.298","14.137","14.288","14.186","13.988","14.156","14.009","14.259","13.861","14.029"'  to have
['1415918_a_at', '13.948', '14.247', '13.965', '14.298', '14.137', '14.288', '14.186', '13.988', '14.156', '14.009', '14.259', '13.861', '14.02']
then perform a join to be in the required format
this should change once we generate our own text files
You can try to parse such a file (below)  to  get a better understanding.
[text_files.zip](https://github.com/genenetwork/genenetwork2/files/9507677/text_files.zip)

2022-09-07 15:53 UTC, Alexanderlacuna commented
@fredmanglis  PS:I tempted this with csv and it does a better job,thanks for this

2022-09-08 10:08 UTC, fredmanglis commented
> > commit [6652c31](https://github.com/genenetwork/genenetwork2/commit/6652c3137ec477e02c8291ee6154f24cc3a4cef2)
> > @Alexanderlacuna
> > You could use Python's inbuilt [CSV module](https://docs.python.org/3.9/library/csv.html) to parse and dump csv files.
> > I notice that `parse_line_csv` 1 splits the line into separate values, only for you to [then rejoin them](https://github.com/genenetwork/genenetwork2/pull/727/commits/6652c3137ec477e02c8291ee6154f24cc3a4cef2#diff-47cc07d4d9855d77c1030d0849ba82b992017d7c6bdf14d04d824e121f53cb14R215-R216). What is the point of that? You are doing an operation only to undo it - this is a performance drag (probably not big, but still a performance drag).
> > The `parse_line_csv` 1 could probably be cleaned up to be clearer on what is happening. The code mutates the `return_list` in a way that is not immediately apparent. It seems to be processing a list of lists, yet parsing a CSV file line would mostly give you non-nested list.
> > I'm still confused about how this function works. Could you give an example.
> > I find it difficult to merge this without understanding it. Maybe add a test with a sample file to be read so as to verify it works as expected.
> > ### Footnotes
> > 1 [`parse_line_csv`](https://github.com/genenetwork/genenetwork2/pull/727/commits/6652c3137ec477e02c8291ee6154f24cc3a4cef2#diff-47cc07d4d9855d77c1030d0849ba82b992017d7c6bdf14d04d824e121f53cb14R191-R195)
> 
> @fredmanglis This has to do with the bad formatting of the current text files being used and makes it impossible to parse with as csv for example the values for each are quoted as shown below '"1415918_a_at","13.948","14.247","13.965","14.298","14.137","14.288","14.186","13.988","14.156","14.009","14.259","13.861","14.029"' to have ['1415918_a_at', '13.948', '14.247', '13.965', '14.298', '14.137', '14.288', '14.186', '13.988', '14.156', '14.009', '14.259', '13.861', '14.02'] then perform a join to be in the required format this should change once we generate our own text files You can try to parse such a file (below) to get a better understanding. [text_files.zip](https://github.com/genenetwork/genenetwork2/files/9507677/text_files.zip)

I just tested this with the file you provided with  [test_read.py.zip](https://github.com/genenetwork/genenetwork2/files/9525901/test_read.py.zip) (extract it in the `text_files` directory) and csv reads the file with no issues as far as I can tell.

Please have a look and get back to me.

2022-09-08 10:14 UTC, fredmanglis commented on wqflask/wqflask/correlation/pre_computes.py
> +            'SELECT Id, FullName FROM ProbeSetFreeze WHERE Name = "%s"' % dataset_name)
Change `"%s"` to `%s` (no double quotes) and don't do string interpolation.

Change the entire thing to:

```python
cursor.execute(
    'SELECT Id, FullName FROM ProbeSetFreeze WHERE Name = %s', dataset_name)
```

**NOTE**: the text of the query (`"SELECT  Id, ..."`) is separated from the parameter (`dataset_name`) with a comma (**,**) not a string interpolation operator (**%**)

2022-09-08 10:14 UTC, fredmanglis requested changes
Change `"%s"` to `%s` (no double quotes) and don't do string interpolation.

Change the entire thing to:

```python
cursor.execute(
    'SELECT Id, FullName FROM ProbeSetFreeze WHERE Name = %s', dataset_name)
```

**NOTE**: the text of the query (`"SELECT  Id, ..."`) is separated from the parameter (`dataset_name`) with a comma (**,**) not a string interpolation operator (**%**)

2022-09-08 11:04 UTC, merged